#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
./Allclean
rm 0 -r
cp 0_org 0 -r
runApplication blockMesh
runApplication  modifyPatches -null wallIB
runApplication topoSet -dict ./system/topoSetDict1
runApplication refineMesh -dict ./system/refineMeshDict -overwrite
rm log.r* log.t*
runApplication topoSet -dict ./system/topoSetDict2
runApplication refineMesh -dict ./system/refineMeshDict -overwrite
rm log.t* log.r*
rm triValues -r
runApplication topoSet -dict ./system/topoSetDict3
runApplication refineMesh -dict ./system/refineMeshDict -overwrite
rm log.t* log.r*
rm triValues -r
runApplication topoSet -dict ./system/topoSetDict4
runApplication refineMesh -dict ./system/refineMeshDict -overwrite
rm log.t* log.r*
rm triValues -r
