#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean triSurfaceFieldTools
wclean immersedBoundary
wclean immersedBoundaryTurbulence
wclean immersedBoundaryForce
wclean immersedBoundarySurfaceToCell
wclean immersedBoundaryDynamicMesh
wclean ibmFvSolutions
wclean ibmFvOptions
wclean ibmFvSchemes

# ----------------------------------------------------------------- end-of-file
