#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake triSurfaceFieldTools
wmake immersedBoundary  
wmake immersedBoundaryTurbulence
wmake immersedBoundaryForce 
wmake immersedBoundarySurfaceToCell
wmake immersedBoundaryDynamicMesh
wmake ibmFvOptions
# ----------------------------------------------------------------- end-of-file
