#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean ibSimpleFoam
wclean ibPimpleFoam
wclean ibMorphFoam

# ----------------------------------------------------------------- end-of-file
