#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake ibSimpleFoam
wmake ibPimpleFoam
wmake ibMorphFoam
# ----------------------------------------------------------------- end-of-file
