#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="ibSimpleFoam"

./makeMesh

#runApplication potentialIbFoam
runApplication $application &
