#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
cp constant/triSurface/IB_bed0.stl constant/triSurface/IB_bed.stl
rm pr* po* -r
#------------------------------------------------------------------------------
