#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
./Allclean
rm 0 -r
cp 0.org 0 -r

runApplication blockMesh
runApplication topoSet -dict ./system/topoSetDict
runApplication refineMesh -dict ./system/refineMeshDict -overwrite
runApplication  modifyPatches -null IB_bed
